# Generated by Django 5.1.1 on 2024-09-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_tags'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(to='tags.tag'),
        ),
    ]
